using Microsoft.Data.Sqlite;
using System.Globalization;
using System.Text;

namespace Grammar.Czech.Lexicon.Tool
{
    /// <summary>
    /// Writes a lexicon database out as portable INSERT statements.
    /// </summary>
    /// <remarks>
    /// The database is a binary file, so git can store it but cannot show what changed inside it. This is
    /// the text form a review reads: the same statements the seed is written in, so a dump can be edited
    /// and fed back through build. Wiring it into the commit workflow is a separate step and is not done
    /// here — the tool only has to be able to produce the file.
    /// </remarks>
    internal static class LexiconDumper
    {
        // Parents before children, so that the dump can be replayed against an empty schema with foreign
        // keys switched on.
        private static readonly (string Table, string[] Columns)[] Tables =
        [
            ("lexicon_meta", ["meta_key", "meta_value"]),
            ("lexeme", ["lexeme_id", "primary_lemma", "note"]),
            ("lemma_entry", [
                "lemma_entry_id", "lemma", "lemma_key", "homonym_index", "category", "gender", "pattern",
                "is_animate", "has_mobile_e", "has_genitive_plural_shortening",
                "has_epenthesis_in_genitive_plural", "is_indeclinable", "is_plural_only", "is_countable",
                "prefers_short_form", "verb_class", "aspect", "aspect_counterpart", "reflexive_type",
                "base_verb_lemma", "lexeme_id", "source", "is_verified", "note"]),
            ("lexical_unit", ["lu_id", "lexeme_id", "sense_label", "gloss", "ssc_class_id"]),
            ("valency_frame", ["frame_id", "lu_id", "kind", "diathesis", "is_default"]),
            ("valency_slot", [
                "slot_id", "frame_id", "functor", "canonical_order", "obligatoriness",
                "can_drop_contextual", "can_drop_generic", "control_target"]),
            ("slot_realization", [
                "realization_id", "slot_id", "morph_case", "preposition", "clause_type",
                "takes_infinitive", "preference"]),
            ("construction", [
                "construction_id", "pattern_name", "light_verb_lemma", "pred_noun_lemma", "template_json"])
        ];

        /// <summary>
        /// Dumps the lexicon at the supplied path.
        /// </summary>
        /// <param name="databasePath">The database to read.</param>
        /// <param name="outputPath">The .sql file to write.</param>
        public static void Dump(string databasePath, string outputPath)
        {
            var connectionString = new SqliteConnectionStringBuilder
            {
                DataSource = databasePath,
                Mode = SqliteOpenMode.ReadOnly
            }.ToString();

            using var connection = new SqliteConnection(connectionString);
            connection.Open();

            var builder = new StringBuilder();
            builder.AppendLine("-- Grammar.Czech — lexicon dump.");
            builder.AppendLine("-- Generated by Grammar.Czech.Lexicon.Tool. Replay against an empty schema.");
            builder.AppendLine();

            foreach (var (table, columns) in Tables)
            {
                AppendTable(connection, builder, table, columns);
            }

            File.WriteAllText(outputPath, builder.ToString(), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
        }

        private static void AppendTable(
            SqliteConnection connection,
            StringBuilder builder,
            string table,
            string[] columns)
        {
            using var command = connection.CreateCommand();

            // Ordered by the primary key, which is the first column of every table here, so that two dumps
            // of the same data compare equal rather than depending on storage order.
            command.CommandText = $"SELECT {string.Join(", ", columns)} FROM {table} ORDER BY {columns[0]}";

            using var reader = command.ExecuteReader();

            var rows = 0;

            while (reader.Read())
            {
                if (rows++ == 0)
                {
                    builder.AppendLine($"-- {table}");
                }

                var values = new string[columns.Length];

                for (var index = 0; index < columns.Length; index++)
                {
                    values[index] = Literal(reader.IsDBNull(index) ? null : reader.GetValue(index));
                }

                builder.AppendLine(
                    $"INSERT INTO {table} ({string.Join(", ", columns)}) VALUES ({string.Join(", ", values)});");
            }

            if (rows > 0)
            {
                builder.AppendLine();
            }
        }

        private static string Literal(object? value) => value switch
        {
            null => "NULL",
            long number => number.ToString(CultureInfo.InvariantCulture),
            int number => number.ToString(CultureInfo.InvariantCulture),
            double number => number.ToString("R", CultureInfo.InvariantCulture),

            // Doubling the apostrophe is the escape every one of the target engines agrees on, which
            // backslash escaping is not.
            _ => "'" + value.ToString()!.Replace("'", "''") + "'"
        };
    }
}
