using Microsoft.Data.Sqlite;
using System.Globalization;
using System.Text;

namespace Grammar.Czech.Lexicon.Tool
{
    /// <summary>
    /// Writes a lexicon database out as portable INSERT statements.
    /// </summary>
    /// <remarks>
    /// The database is a binary file, so git can store it but cannot show what changed inside it. This is
    /// the text form a review reads: the same statements the seed is written in, so a dump can be edited
    /// and fed back through build. Wiring it into the commit workflow is a separate step and is not done
    /// here — the tool only has to be able to produce the file.
    /// </remarks>
    public static class LexiconDumper
    {
        /// <summary>
        /// Dumps the lexicon at the supplied path.
        /// </summary>
        /// <param name="databasePath">The database to read.</param>
        /// <param name="outputPath">The .sql file to write.</param>
        public static void Dump(string databasePath, string outputPath)
        {
            var connectionString = new SqliteConnectionStringBuilder
            {
                DataSource = databasePath,
                Mode = SqliteOpenMode.ReadOnly
            }.ToString();

            using var connection = new SqliteConnection(connectionString);
            connection.Open();

            var builder = new StringBuilder();
            builder.AppendLine("-- Grammar.Czech — lexicon dump.");
            builder.AppendLine("-- Generated by Grammar.Czech.Lexicon.Tool. Replay against an empty schema.");
            builder.AppendLine();

            // LexiconSchema orders the tables parents first, which is also what a replay against an empty
            // schema with foreign keys switched on needs.
            foreach (var table in LexiconSchema.Tables)
            {
                AppendTable(connection, builder, table.Name, table.Columns);
            }

            File.WriteAllText(outputPath, builder.ToString(), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));

            connection.Close();

            // Pooling keeps the file open past Dispose, and a dump is often the last thing done to a
            // database before it is replaced or thrown away.
            SqliteConnection.ClearAllPools();
        }

        private static void AppendTable(
            SqliteConnection connection,
            StringBuilder builder,
            string table,
            IReadOnlyList<string> columns)
        {
            using var command = connection.CreateCommand();

            // Ordered by the primary key, which is the first column of every table here, so that two dumps
            // of the same data compare equal rather than depending on storage order.
            command.CommandText = $"SELECT {string.Join(", ", columns)} FROM {table} ORDER BY {columns[0]}";

            using var reader = command.ExecuteReader();

            var rows = 0;

            while (reader.Read())
            {
                if (rows++ == 0)
                {
                    builder.AppendLine($"-- {table}");
                }

                var values = new string[columns.Count];

                for (var index = 0; index < columns.Count; index++)
                {
                    values[index] = Literal(reader.IsDBNull(index) ? null : reader.GetValue(index));
                }

                builder.AppendLine(
                    $"INSERT INTO {table} ({string.Join(", ", columns)}) VALUES ({string.Join(", ", values)});");
            }

            if (rows > 0)
            {
                builder.AppendLine();
            }
        }

        private static string Literal(object? value) => value switch
        {
            null => "NULL",
            long number => number.ToString(CultureInfo.InvariantCulture),
            int number => number.ToString(CultureInfo.InvariantCulture),
            double number => number.ToString("R", CultureInfo.InvariantCulture),

            // Doubling the apostrophe is the escape every one of the target engines agrees on, which
            // backslash escaping is not.
            _ => "'" + value.ToString()!.Replace("'", "''") + "'"
        };
    }
}
